{
  "config": {
    "step": {
      "user": {
        "data": {
          "description": "Verbinde dich mit deiner Ladestation, wenn die IP-Adresse nicht eingestellt ist, wird die automatische Erkennung verwendet",
          "host": "Host (IP Adresse)"
        }
      }
    },
    "error": {
      "cannot_connect": "Verbindung zur Ladestation nicht möglich.",
      "unknown": "Unbekannter Fehler. Bitte überprüfe die Log Datei.",
      "no_device_found": "Keine Ladestation im Netzwerk gefunden."
    },
    "abort": {
      "already_configured": "Ladestation bereits konfiguriert."
    }
  },
  "options": {
    "step": {
      "init": {
        "data": {
          "failsafe": "Failsafe mode",
          "failsafe_timeout": "Failsafe timeout (in Sekunden)",
          "failsafe_fallback": "Failsafe fallback current (in Ampere)",
          "failsafe_persist": "Failsafe persistieren",
          "rfid": "RFID tag für default Authentication (Optional)",
          "rfid_class": "RFID class für default Authentication (Farbcode, optional)"
        }
      }
    }
  },
  "issues": {
    "deprecated_yaml": {
      "description": "Ihre bestehende YAML-Konfiguration wurde automatisch in die Benutzeroberfläche importiert.\n\nEntfernen Sie die keba YAML-Konfiguration aus Ihrer configuration.yaml-Datei und starten Sie Home Assistant neu, um dieses Problem zu beheben.\n\nAufgrund interner Umstrukturierungen müssen Sie möglicherweise Automationen, Skripte und Ihr Dashboard aktualisieren.",
      "title": "Die YAML-Konfiguration von Keba wird nicht mehr verwendet."
    }
  }
}
